first=int(input("Enter your first number "))
second=int(input("Enter your second number "))
print(f"The sum of {first} and {second} is = {first+second}")
print(f"The quotient of {first} and {second} is = {first/second}")
print(f"The product of {first} and {second} is = {first*second}")
print(f"The difference of {first} and {second} is = {first-second}")
